services:
  beszel:
    image: henrygd/beszel:latest
    restart: unless-stopped
    expose:
      - "8090"
    volumes:
      - beszel-data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PORT=45876
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILpRKJEvnMrczfFye8ofP9h/qhMkZ+u7IEvqVV3emkI/

volumes:
  beszel-data:
